import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import { useState, useEffect } from "react";
import axios from "axios";
import Menu1 from "../comps/Menu1";
import Button from '../comps/Button';


export default function Journal() {
  const [file, setFile] = useState();
  //const [title, setTitle] = useState("");
  const [description, setDescription] = useState("");
  const [tag, setTag] = useState("");
  const [tags, setTags] = useState(["sample", "tag1"]);
  const [posts, setPosts] = useState([]);


  const submit = async (event) => {
    event.preventDefault();
    const data = new FormData();
    data.append("image", file);
   // data.append("title", title);
    data.append("description", description);
    data.append("tags", tags);
    const result = axios.post("/posts", data);  
    console.log("result", result);
 
   
  };

  const removeTag = (i) => {
    // console.log("i", i);
    const newTags = tags.filter((e, idx) => idx !== i);
    // console.log("tags", tags)
    // console.log("newTags", newTags);
    setTags(newTags);
  };

  const addTag = (e) => {
    if (e.key === "Enter") {
      console.log("value", e.target.value);
      console.log("tag", tag);
      setTags([...tags, tag]);
      console.log("tags", tags);
      e.target.value = "";
    }
  };

  

  return (
    <div className={styles.container}>
      <div className={styles.holder1}>
        <Menu1 journsrc="journalActive.svg"/>
      </div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Journal</h1>
        <form id="newJournalForm" onSubmit={submit}>
          <input
            filename={file}
            onChange={(e) => setFile(e.target.files[0])}
            type="file"
            accept="image/*"
          ></input>
          <h4>Description</h4>
          <textarea
            onChange={(e) => setDescription(e.target.value)}
            type="text"
            placeholder="Journal starts here"
          ></textarea>

          <h4>Click here to submit</h4>
          <Button routeTo="./myprofile" ButtonText="Submit" type="submit"/>
         {/* <button type="submit" >Submit</button> */}
          {/* <button type="submit"onClick={() => Router.push('/myprofile')}>Submit to profile page</button>  */}
          
        </form>
        <h4>Tags</h4>
       
        <div id="content">
          <ul id="lists">
            {/* <li>{tags}</li> */}
            {tags.map((t, i) => (
              <li key={t}>
                {t}
                <button
                  type="button"
                  onClick={() => {
                    removeTag(i);
                  }}
                >
                  -
                </button>
              </li>
            ))}
          </ul>
          <input
            type="text"
            onChange={(e) => setTag(e.target.value)}
            onKeyPress={addTag}
          ></input>
        </div>
        
      </main>
    </div>
  );
}
